services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./laravel-stresscheck:/var/www/html
    networks:
      - laravel

  composer:
    image: composer:latest
    container_name: laravel_composer
    working_dir: /var/www/html
    volumes:
      - ./laravel-stresscheck:/var/www/html
    entrypoint: ["composer"]

  web:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "8081:80"
    volumes:
      - ./laravel-stresscheck:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: laravel_dbs
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge